# Generated by Django 2.2.16 on 2023-02-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Можно написать комментарий', verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Тут можно загрузить картинку', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
